// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pos.Api.DataAccess;

namespace Pos.Api.DataAccess.Migrations
{
    [DbContext(typeof(PosDBContext))]
    partial class PosDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pos.Api.DataAccess.Contracts.Entities.ExternalUserEntity", b =>
                {
                    b.Property<int>("IdTercero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DireccionTercero1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionTercero2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaInscripcionTercero")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreTercero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObservacionTercero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonoTercero1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonoTercero2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonoTercero3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoTercero")
                        .HasColumnType("int");

                    b.HasKey("IdTercero");

                    b.ToTable("ExternalUser");
                });

            modelBuilder.Entity("Pos.Api.DataAccess.Contracts.Entities.ProductEntity", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CantidadEnBodega")
                        .HasColumnType("int");

                    b.Property<int>("CantidadMaxima")
                        .HasColumnType("int");

                    b.Property<int>("CantidadMinima")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaProducto")
                        .HasColumnType("int");

                    b.Property<int>("CodigoBarras")
                        .HasColumnType("int");

                    b.Property<string>("DescripcionProducto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdImpuesto")
                        .HasColumnType("int");

                    b.Property<string>("NombreProducto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoProducto")
                        .HasColumnType("int");

                    b.Property<int>("UnidadMedida")
                        .HasColumnType("int");

                    b.HasKey("IdProducto");

                    b.ToTable("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
